config/routes.rb
Rails.application.routes.draw do
	get 'blogs/index'
   root 'blogs#index'
  
  
   get 'welcome/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

   resources :blogs do
  resources :comments do
    resources :replies
     get '/contact', to:'blogs/#contact'

    end
  end

  post '/likes' => 'likes#create', as: :like_create
  post '/dislikes' => 'likes#dislike', as: :dislike_create
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
   mount_uploader :image, ImageUploader	

     has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }

                   

   def self.search(search)
      where("title LIKE ?" , "%#{search}%") 
   end
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog 
  has_many :replies, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
 
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :likeable, polymorphic: true
	 def self.create_like(comment, current_user)
		 like = Like.find_or_initialize_by(:likeable=>comment,:user_id=>current_user.id)
		 if like.like
		 like.destroy
		 else
		 like.like= true
		 like.save
		 end
	 end

	 def self.create_dislike(comment, current_user)
		 like = Like.find_or_initialize_by(:likeable=>comment,:user_id=>current_user.id)
		 if like.like==false
		 like.destroy
		 else
		 like.like= false
		 like.save
		 end
	 end
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :comment
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
      
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 def is_liked(comment)
	 if Like.where(:likeable => comment ,:user_id => self.id).present?
	 Like.where(:likeable => comment ,:user_id => self.id).last.like==true
	 end
 end

 def is_disliked(comment)
	 if Like.where(:likeable => comment ,:user_id => self.id).present?
	 Like.where(:likeable => comment ,:user_id => self.id).last.like==false
	 end
 end

 def self.find_comment(id, type)
	 comment= type.constantize.find(id)
	 return comment
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
	#before_action :configure_permitted_parameters, if: :devise_controller?
end

app/controllers/blogs_controller.rb
class BlogsController < InheritedResources::Base
  def index
    @blogs = Blog.all
    if params[:search]
      @blogs = Blog.search(params[:search]).order("created_at DESC")
    else
      @blogs = Blog.all.order("created_at DESC")
    end
  end
  

  private
    def blog_params
      params.require(:blog).permit(:title, :image, :category, :description)
    end   
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  #before_action :comment
  #before_action :comment, only: [:destroy, :edit, :update]
  def new
    @comment = Comment.new(:blog_id => [:blog_id])
  end
  
	def create
    @blog = Blog.find(params[:blog_id])
    @comment = @blog.comments.create(comment_params)
    redirect_to blog_path(@blog)
  end

  def destroy
    @blog = Blog.find(params[:blog_id])
    @comment = @blog.comments.find(params[:id])
    @comment.destroy
    redirect_to blog_path(@blog)
  end

  def edit
    @blog = Blog.find(params[:blog_id])
    @comment = @blog.comments.find(params[:id])
  end
  
  
  def update
    @blog = Blog.find(params[:blog_id])
    @comment = @blog.comments.find(params[:id])
    if @comment.update(comment_params)
    redirect_to blog_path(@blog)
    else
    render 'edit'
    end
  end
   

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :set_comment
	def create
	 Like.create_like(@comment, current_user)
	end

	def dislike
	 Like.create_dislike(@comment, current_user)
	end

	def set_comment
	 @comment=User.find_comment(params[:id], params[:type])
	end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
	before_action do
		@comment = Comment.find(params[:comment_id])
		@blog = Blog.find(params[:blog_id])
	end

	def index
		@replies = @comment.replies
		@reply = @comment.replies.new	
	end

	def new
		@reply = @comment.replies.new
	end


	def create
    @reply = Reply.new(:body=>params[:reply][:body],:comment_id=>params[:reply][:comment_id])
    if @reply.save
	    flash[:notice]="replies created"
	    respond_to do |format|
	    	format.html
	   		format.js { render action: "create", :locals => {comment_id: params[:reply][:comment_id]} }
	 	  end
 		end
  end

  def show
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def count_like(comment)
      comment.likes.where(like: true).count
    end
    
    def count_dislike(comment)
      comment.likes.where(like: false).count
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>
      <ul>
        <% blog.errors.full_messages.each do |message| %>
         <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <table border="2" align="center" style="background: linear-gradient(to bottom, #33ccff 0%,
      #ff99cc 100%)" width="20%" height="100px">
      
      
      
      
    <tr align="center">
      <td align="center">
        <div class="field">
         <%= form.label :title %>
         <%= form.text_field :title %>
        </div>
      </td>
      <td>

         <div class="field">
          <%= form.label :image %>
          <%= form.file_field :image %>
        </div>
      </td>
      <td>
        <div class="field">
         <%= form.label :category %>
         <%= form.select(:category, Category.all.collect {|u| [u.name, u.id]}, :prompt => 'Select') %> 
        </div> 
      </td>
      <td>
        <div class="field">
         <%= form.label :description %>
         <%= form.text_field :description, :cols => 30, :rows => 30 %>
        </div>
      </td>
    </tr>
  </table>
  <br>
  <table>
  <tr>    
        <div class="actions" align="center">
         <%= form.submit "Create Blog", class: "btn btn-primary" %>
        </div>
      
    </tr>
  </table>
<% end %>

app/views/blogs/contact.html.erb
<h1>NAME-----Shikha Pandey</h1>
<br>
<h1>CONTACT NUMBER--9670818439</h1>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>
<%= render 'form', blog: @blog %>
<br>
<%= link_to 'Show', @blog, class: "btn btn-primary" %> |
<%= link_to 'Back', blogs_path, class: "btn btn-primary" %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Blogs</h1>
<table class="table">
  <thead> 
    <tr>
      <th>Title</th>
      <th>Image</th>
      <th>Category</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        
        <td><%= image_tag blog.image_url.to_s %></td>
        <td>
          <% if blog.category.present? %>
           <%= Category.find(blog.category).name %>
          <% end %> 
        </td>
        <td><%= blog.description %></td>
        <td><%= link_to 'Show', blog , class: "btn btn-primary"%></td>
        <td><%= link_to 'Edit', edit_blog_path(blog), class: "btn btn-primary" %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<% if @blogs.blank? %>
  <h4>Result can not found <%= params[:search] %>.</h4>
<% end %>
<%= link_to 'New Blog', new_blog_path, class: "btn btn-primary" %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>
<%= render 'form', blog: @blog %>
<br>
<%= link_to 'Back', blogs_path, class: "btn btn-primary" %>

app/views/blogs/show.html.erb
<html>
	<head>
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
		<style>
			.fa {
			    font-size: 50px;
			    cursor: pointer;
			    user-select: none;
			}

			.fa:hover {
			  color: darkblue;
			}
		</style>
	</head>

	<p id="notice"><%= notice %></p>
	<table border="3px" width="70%" align="center">
		<tr>
		  <td align="center">
	      <p>
					<strong>Title:</strong>
					<%= @blog.title %>
				</p>
	    </td>
		  <td align="center">
				<p>
					<strong>Category:</strong>
					<% if @blog.category.present? %>
				      <%= Category.find(@blog.category).name %>
				   <% end %>
				</p>
		  </td>
		  <td align="center">
				<p>
					<strong>Image:</strong>
					<%= image_tag @blog.image_url(:thumb).to_s %>
				</p>
		  </td>
		  <td align="center">
	      <p>
					<strong>Description:</strong>
					<%= @blog.description %>
				</p>
		  </td>
		</tr>
	</table>
 
		<table border="3px" width="70%" align="center">
			<tr align="center">
					<td align="center">
						<h2>Comments</h2>
					  <%= render @blog.comments %>
					</td>

					<td>
						<h2>Add a comment:</h2>
						<%= render 'comments/form' %>
					</td>
				</tr>
			</table>
			<br>
			<table border="3px" width="70%" align="center">
				<tr align="center">
				  <td align="center">		
						<%= link_to 'Edit', edit_blog_path(@blog), class: "btn btn-primary" %> |
					
						<%= link_to 'Back', blogs_path, class: "btn btn-primary" %>
					</td>
		  </tr>
		</table>
</html>	

app/views/comments/_comment.html.erb
<table border="2px">
  <td>
    <p>
      <strong>Commenter:</strong>
      <%= comment.commenter %>
    </p>
   
    <p>
      <strong>Comment:</strong>
      <%= comment.body %>
    </p>
   
    <p>
      <%= link_to 'Destroy Comment', [comment.blog, comment],
                   method: :delete,
                   data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>

      <%= link_to "Edit comment", edit_blog_comment_path(comment.blog, comment), class: "btn btn-primary" %>
      <%#= link_to "Reply", new_blog_comment_reply_path(comment.blog, comment), class: "btn btn-primary" %>
    </p>

    <h3>reply a comment</h3>
    <% @replies= Reply.where(:comment_id=> comment) %>
    <% @replies.each do |reply| %>
    <p>
      <br>
      <strong>Reply</strong>
      <%=reply.body%>
    </p>
     
    <%end%>
     
    <div id="reply-container"></div>
  </td>
</table>

<%= render :partial => 'replies/form', locals: {blog: @blog, comment: comment, reply: comment.replies.new} %>
<%= render partial: "likes/like", locals: {comment: comment } %> 

app/views/comments/_form.html.erb
<%= form_with(model: [@blog, @blog.comments.build], local: true) do |form| %>
 <%#= form_with(model: @comment, local: true) do |form| %>

  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>

  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>

  <p>
    <%= form.submit "Create Comment", class: "btn btn-primary" %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<h1> Edit Comment</h1>
<%= form_with(model: [@blog, @comment], local: true) do |form| %>
    <%#= form_with(model: @comment, local: true) do |form| %>

  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>

  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    
    
        
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">BLOGGER</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="/blogs/index">Home</a></li>
              <li><a href="/blogs/new">New Blog</a></li>
              <li><a href="/users/sign_up">Registration</a></li>
              <li><a href="/users/sign_in">Login</a></li>


              
              <!--<li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li role="separator" class="divider"></li>
                  <li class="dropdown-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>-->
            </ul>
            <!--<ul class="nav navbar-nav navbar-right">
              <li class="active"><a href="./">Default <span class="sr-only">(current)</span></a></li>
              <li><a href="../navbar-static-top/">Static top</a></li>
              <li><a href="../navbar-fixed-top/">Fixed top</a></li>
            </ul>-->
          </div>
        </div>
      </nav>
      <table border="2" align="center" style="background: linear-gradient(to bottom, #33ccff 0%,
       #ff99cc 100%)" width="20%">
        <td>
          <%= form_tag(blogs_path, :method => "get", id: "search-form") do %>
           <%= text_field_tag :search, params[:search], placeholder: "Search Blogs" %>
           <%= submit_tag "Search", :name => nil, class: "btn btn-info" %>
          <% end %>
        </td>
      </table>
      <br>
      <br>
      <table border="2" align="center" style="background: linear-gradient(to bottom, #33ccff 0%,
       #ff99cc 100%)" width="20%">
        
        <td>
          <div class="container" align="center">
            <div id="user_nav">
              <% if user_signed_in? %>
                Signed in as <%= current_user.email %>. Not you?
                <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
              <% else %>
              <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
              <% end %>
            </div>
            <%= yield %>
         </div>
         <footer class="footer">
            <div class="footer">
              <p style="color:red;"><font color="red">blog-demo &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <a href="https://www.w3schools.com">W3Schools.com</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <a href="https://www.w3schools.com/html/">HTML Tutorial</a></p>

            </div>
         </footer>
        </td>
      </table>
  </body>
</html>  

<style type="text/css">
  body {
  background-image: url("<%= asset_path("logos/12.jpg")%>");
   background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
    background-attachment: fixed;
    }
</style>

app/views/likes/_like.html.erb
<div id= "like_<%= comment.class.name %>_<%= comment.id %>"> 
    <!--Like-->
	(<%=count_like(comment)%>)
	<% if current_user.is_liked(comment) %>
	<%= link_to "liked", like_create_path(id: comment.id, type: comment.class.name), method: :post, remote: true %>
	<%else%>
			<%= link_to "like", like_create_path(id: comment.id, type: comment.class.name), method: :post, remote: true, class: "btn btn-primary" %>
			<%end%>

	<!--dislike-->

  (<%= count_dislike(comment)%>)
	<% if current_user.is_disliked(comment) %>
		<%= link_to "Disliked", dislike_create_path(id: comment.id, type: comment.class.name), method: :post, remote: true %>
				<%else%>
				<%= link_to "Dislike", dislike_create_path(id: comment.id, type: comment.class.name), method: :post, remote: true, class: "btn btn-primary" %>
			<%end%>

</div>

app/views/likes/create.js.erb
$("#like_<%= @comment.class.name%>_<%= @comment.id %>").html("<%= j(render partial: 'likes/like', locals: {comment: @comment}) %>")

app/views/likes/dislike.js.erb
$("#like_<%= @comment.class.name%>_<%= @comment.id %>").html("<%= j(render partial: 'likes/like', locals: {comment: @comment}) %>")

app/views/replies/_all_replies.html.erb
<h3>reply a comment</h3>
    <% @replies= Reply.where(:comment_id=> comment) %>
    <% @replies.each do |reply| %>
  	<p>
  		<strong>Reply</strong>
  		<%=reply.body%>
  	</p>

  	<%end%>

app/views/replies/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
	 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
<%= link_to "Reply", new_blog_comment_reply_path(comment.blog, comment) %>

app/views/replies/_form.html.erb
<%= form_for([blog, comment, reply], remote: true) do |f| %>
 <%= f.hidden_field :comment_id, :value=> comment.id %>
 <%= f.text_field :body %>
 <%= f.submit  "Reply", class: "btn btn-primary" %>
<%end%>

app/views/replies/create.js.erb
$('#reply-container').html("<%= j render(:partial => 'replies/all_replies.html', :locals => { :comment => comment_id }) %>");

app/views/replies/new.html.erb
<%= render 'form' blog: @blog, comment: @comment, reply: @reply %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>